<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_SECRET' => '3879552cfc9a0dec35971cd7b8fbd348',
  'DATABASE_URL' => 'postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=16&charset=utf8',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'API_KEY' => 'APK-6e6eca93-5ce1-471a-bd4a-ceb639878e48',
  'API_URL' => 'https://env-4705878.sh1.hidora.com/',
);
